apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: charmiy
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: charmiy  # Corrected namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181  # Retyped line to remove any non-breaking spaces

          resources:
            requests:
              cpu: "400m"  # Minimum CPU requested
              memory: "128Mi"  # Minimum memory requested
#            limits:
#              cpu: "500m"  # Maximum CPU allowed
#              memory: "512Mi"  # Maximum memory allowed
