apiVersion: apps/v1
kind: Deployment
metadata:
  name: promt-microservice
  namespace: charmiy
  labels:
    app: promt-microservice
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: promt-microservice
  template:
    metadata:
      labels:
        app: promt-microservice
    spec:
      containers:
        - name: promt-microservice
          image: consforc/charmiy-prompts-microservice
          ports:
            - containerPort: 5006
          env:
            - name: NODE_ENV
              value: development
            - name: REDIS_URL
              value: "redis://redis-service:6379"  # Point to the Redis service
            - name: KAFKA_BROKER
              value: "kafka:9092"  # Replace with the actual Kafka broker service name and port

          resources:
            requests:
              cpu: "400m"  # Minimum CPU requested
              memory: "128Mi"  # Minimum memory requested
#            limits:
#              cpu: "500m"  # Maximum CPU allowed
#              memory: "512Mi"  # Maximum memory allowed
---
apiVersion: v1
kind: Service
metadata:
  name: promt-microservice
  namespace: charmiy
spec:
  ports:
    - port: 5006
      targetPort: 5006
  selector:
    app: promt-microservice
  type: ClusterIP
